ALTER TABLE todo.tasks DROP COLUMN IF EXISTS completed_at RESTRICT;

ALTER TABLE todo.history ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE todo.history ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;