ALTER TABLE todo.tasks ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;

ALTER TABLE todo.history DROP COLUMN IF EXISTS row_version CASCADE;
ALTER TABLE todo.history DROP COLUMN IF EXISTS updated_at RESTRICT;